
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")


def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')


platform :ios, '15.1'

use_frameworks! :linkage => :static 

prepare_react_native_project!
setup_permissions([
  'AppTrackingTransparency',
  'Bluetooth',
  'Calendars',
  'CalendarsWriteOnly',
  'Camera',
  'Contacts',
  'FaceID',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'MediaLibrary',
  'Microphone',
  'Motion',
  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
  'Reminders',
  'Siri',
  'SpeechRecognition',
  'StoreKit',
])



target 'FoodHub' do
  use_expo_modules! # Setup expo modules
  pod 'gRPC-C++', '~> 1.65.0'
  pod 'gRPC-Core', '~> 1.65.0'
  pod 'Firebase/CoreOnly', '11.8.0'
  pod 'FirebaseFirestore', '11.8.0'
  
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  rn_maps_path = '../node_modules/react-native-maps'
    pod 'react-native-google-maps', :path => rn_maps_path

  # Autolinking configuration for react-native
  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = [
      'node',
      '-e',
      "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"
    ]
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  # Include react-native-maps with Google Maps support
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  # Use React Native dependencies
  config = use_native_modules!(config_command)

  use_react_native!(
    :path => config[:reactNativePath],
    # Absolute path to your application root
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Tests target
  target 'FoodHubTests' do
    inherit! :complete
  end

  # Post-install configurations
  post_install do |installer|
    # React Native post-install setup
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
