export default {
  SPLACE: require('../assets/Splash.png'),
  Intro1Light: require('../assets/intro.png'),
  Intro2Light: require('../assets/intro1.png'),
  Intro3Light: require('../assets/intro2.png'),
  Res1: require('../assets/res1.jpg'),
  Res2: require('../assets/res2.jpg'),
  Res3: require('../assets/res3.jpg'),
  Res4: require('../assets/res4.jpg'),
  Res5: require('../assets/res5.jpg'),
  Res6: require('../assets/res6.jpg'),
  Res7: require('../assets/res7.jpg'),
  Bir: require('../assets/bir.jpg'),
  Bug: require('../assets/bug.jpg'),
 
  Fast: require('../assets/fast.jpg'),
  Lun: require('../assets/lun.jpg'),
  Din: require('../assets/din.jpg'),
  Piz: require('../assets/piz.jpg'),
  Profile: require('../assets/profile.png'),
  COD: require('../assets/cod.jpg'),
  UPI: require('../assets/upi.jpg'),
  CARD: require('../assets/card.jpeg'),
  CARD1: require('../assets/card1.png'),

  // APP_ICON: require('../assets/APP_ICON.png'),
  // HatchBack: require('../assets/HatchBack.png'),
  // Sedan: require('../assets/Sedan.png'),
  // SUV: require('../assets/SUV.png'),
  // Scooty: require('../assets/Scooty.png'),
  // HatchBackMap: require('../assets/HatchBackMap.png'),
  // SedanMap: require('../assets/SedanMap.png'),
  // SUVMap: require('../assets/SUVMap.png'),
  // ScootyMap: require('../assets/ScootyMap.png'),
  // AutoMap: require('../assets/AutoMap.png'),
  // Auto: require('../assets/Auto.png'),
  // ScootyAdv: require('../assets/ScootyAdv.png'),
  // Apple_Pay: require('../assets/Apple_Pay.png'),
  // CREDIT_CARD: require('../assets/CREDIT_CARD.jpeg'),
  // UPI: require('../assets/UPI.jpeg'),
  // CashOnDelivery: require('../assets/CashOnDelivery.png'),
  // Profile: require('../assets/Profile.webp'),
  // Intro1Light: require('../assets/Intro1Light.png'),
  // Intro2Light: require('../assets/Intro2Light.png'),
  // Intro3Light: require('../assets/Intro3Light.png'),
  // Intro1Dark: require('../assets/Intro1Dark.png'),
  // Intro2Dark: require('../assets/Intro2Dark.png'),
  // Intro3Dark: require('../assets/Intro3Dark.png'),
  // RiderTypeDark: require('../assets/RiderTypeDark.png'),
  // RiderTypeLight: require('../assets/RiderTypeLight.png'),
  // CustomerTypeDark: require('../assets/CustomerTypeDark.png'),
  // CustomerTypeLight: require('../assets/CustomerTypeLight.png'),
};
